### ISSUE TITLE
Add function to create CITATION.cff from codemeta.json

### ISSUE THREAD

**Issue by Bisaloo** [dieghernan/cffr#32]
I think most people in the R community have been using the `codemeta.json` approach until now (especially since it was encouraged by rOpenSci).

Now that GitHub has integrated `CITATION.cff` in their UI, people might want to switch. It would be amazing if the package could include a conversion function.

I can try to work on a PR if you're interested but don't have time to dedicate to this :relaxed:

**Comment by dieghernan** [comment]
Thanks for the suggestion:

That functionality is already supported on the dev version of **handlr** (see https://github.com/ropensci/handlr/pull/25) so I am not sure if that would fit in **cffr**. I already did some work on that direction with the **bibtex** functions and I have to admit that it was not my best idea, since the package (that has indeed a very simple goal) can start losing focus.

Anyway, if at some point you can prepare a PR for this package, or for improving **handlr**, happy to support and help with it.

cc: @ThierryO @sckott

``` r
# options(repos = c(
#   ropensci = 'https://ropensci.r-universe.dev',
#   CRAN = 'https://cloud.r-project.org'))
# 
# 
# Install some packages
# install.packages('handlr')

library(handlr)
#> Warning: package 'handlr' was built under R version 4.1.3
library(cffr)
#> Warning: package 'cffr' was built under R version 4.1.2

tmpcff <- tempfile(fileext = ".cff")

obj <- cffr::cff_write("dplyr", 
                       outfile = tmpcff,
                       verbose = FALSE)

# Read 
read <- handlr::cff_reader(tmpcff)

handlr::codemeta_writer(read)
#> {
#>   "@type": "SoftwareSourceCode",
#>   "codeRepository": "https://dplyr.tidyverse.org",
#>   "title": "dplyr: A Grammar of Data Manipulation",
#>   "agents": [
#>     {
#>       "type": "Person",
#>       "name": "Hadley Wickham",
#>       "givenName": "Hadley",
#>       "familyName": "Wickham",
#>       "orcid": "https://orcid.org/0000-0003-4757-117X"
#>     },
#>     {
#>       "type": "Person",
#>       "name": "Romain François",
#>       "givenName": "Romain",
#>       "familyName": "François",
#>       "orcid": "https://orcid.org/0000-0002-2444-4226"
#>     },
#>     {
#>       "type": "Person",
#>       "name": "Lionel Henry",
#>       "givenName": "Lionel",
#>       "familyName": "Henry"
#>     },
#>     {
#>       "type": "Person",
#>       "name": "Kirill Müller",
#>       "givenName": "Kirill",
#>       "familyName": "Müller",
#>       "orcid": "https://orcid.org/0000-0002-1416-3412"
#>     }
#>   ],
#>   "description": "A fast, consistent tool for working with data frame like objects, both in memory and out of memory.",
#>   "version": "1.0.8",
#>   "tags": ["data-manipulation", "grammar", "r"],
#>   "datePublished": "2022-02-08"
#> }
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Bisaloo** [comment]
Oh, I didn't know about handlr. I guess my use case is addressed then. Thanks for your answer.
